/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./src/components/Body.vue')['default']
    Collaborator: typeof import('./src/components/Collaborator.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Milestones: typeof import('./src/components/Milestones.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
